version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - /data/docker/demo-docker/nginx/config:/etc/nginx
      - /data/docker/demo-docker/nginx/log:/var/log/nginx
      - /data/docker/demo-docker/www:/var/www/html
    ports:
      - 8000:80
    